export const forecastResponse = {
  location: {
    name: "Denver",
    region: "Colorado",
    country: "USA",
    lat: 39.7392,
    lon: -104.9903,
    tz_id: "America/Denver",
    localtime_epoch: 1674844800,
    localtime: "2025-01-28 10:00",
  },
  current: {
    last_updated_epoch: 1674841200,
    last_updated: "2025-01-28 09:00",
    temp_c: -2.3,
    temp_f: 27.9,
    is_day: 1,
    condition: {
      text: "Partly Cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 5.8,
    wind_kph: 9.4,
    wind_degree: 180,
    wind_dir: "S",
    pressure_mb: 1013,
    pressure_in: 29.91,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 65,
    cloud: 50,
    feelslike_c: -4.0,
    feelslike_f: 24.8,
    windchill_c: -4.0,
    windchill_f: 24.8,
    heatindex_c: -2.3,
    heatindex_f: 27.9,
    dewpoint_c: -8.0,
    dewpoint_f: 17.6,
    vis_km: 10.0,
    vis_miles: 6.2,
    uv: 2.0,
    gust_mph: 8.0,
    gust_kph: 12.9,
  },
  forecast: {
    forecastday: [
      {
        date: "2025-01-28",
        date_epoch: 1674844800,
        day: {
          maxtemp_c: 2.0,
          maxtemp_f: 35.6,
          mintemp_c: -8.0,
          mintemp_f: 17.6,
          avgtemp_c: -3.0,
          avgtemp_f: 26.6,
          maxwind_mph: 10.5,
          maxwind_kph: 16.9,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.2,
          avghumidity: 60,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Partly Cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          uv: 2.0,
        },
        astro: {
          sunrise: "07:12 AM",
          sunset: "05:18 PM",
          moonrise: "08:45 PM",
          moonset: "09:23 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: 75,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1674844800,
            time: "2025-01-28 10:00",
            temp_c: -2.3,
            temp_f: 27.9,
            is_day: 1,
            condition: {
              text: "Partly Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 180,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 50,
            feelslike_c: -4.0,
            feelslike_f: 24.8,
            windchill_c: -4.0,
            windchill_f: 24.8,
            heatindex_c: -2.3,
            heatindex_f: 27.9,
            dewpoint_c: -8.0,
            dewpoint_f: 17.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.2,
            gust_mph: 8.0,
            gust_kph: 12.9,
            uv: 2.0,
          },
          // Additional hourly data can be added here
        ],
      },
    ],
  },
};
